default_platform(:ios)

platform :ios do
  desc "Build and upload to TestFlight"
  lane :beta do
    build_app(
      workspace: "Runner.xcworkspace",
      scheme: "Runner",
      export_method: "app-store",
      export_options: {
        signingStyle: "automatic",
        uploadBitcode: false,
        uploadSymbols: true
      }
    )
    upload_to_testflight(
      skip_waiting_for_build_processing: true
    )
  end

  desc "Build IPA only (no upload)"
  lane :build do
    build_app(
      workspace: "Runner.xcworkspace",
      scheme: "Runner",
      export_method: "app-store",
      export_options: {
        signingStyle: "automatic",
        uploadBitcode: false,
        uploadSymbols: true
      }
    )
  end

  desc "Upload to App Store (production)"
  lane :release do
    build_app(
      workspace: "Runner.xcworkspace",
      scheme: "Runner",
      export_method: "app-store",
      export_options: {
        signingStyle: "automatic",
        uploadBitcode: false,
        uploadSymbols: true
      }
    )
    upload_to_app_store(
      skip_metadata: true,
      skip_screenshots: true,
      force: true
    )
  end
end
