default_platform(:android)

platform :android do
  desc "Upload AAB to Google Play Internal Testing track"
  lane :deploy_internal do
    upload_to_play_store(
      track: 'internal',
      aab: '../build/app/outputs/bundle/release/app-release.aab',
      skip_upload_metadata: true,
      skip_upload_images: true,
      skip_upload_screenshots: true,
      release_status: 'draft'
    )
  end

  desc "Upload AAB to Google Play Closed Testing track"
  lane :deploy_closed do
    upload_to_play_store(
      track: 'alpha',
      aab: '../build/app/outputs/bundle/release/app-release.aab',
      skip_upload_metadata: true,
      skip_upload_images: true,
      skip_upload_screenshots: true,
      release_status: 'draft'
    )
  end

  desc "Upload AAB to Google Play Production"
  lane :deploy_production do
    upload_to_play_store(
      track: 'production',
      aab: '../build/app/outputs/bundle/release/app-release.aab',
      release_status: 'draft'
    )
  end

  desc "Upload metadata and screenshots"
  lane :upload_metadata do
    upload_to_play_store(
      track: 'production',
      skip_upload_aab: true,
      skip_upload_apk: true
    )
  end
end
