name: Test Trigger

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths: ['monorepo/backend/**', 'monorepo/admin/**']

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Actions are working!"
